/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ExFormSearch: typeof import('@element-go/components')['ExFormSearch']
    ExLayout: typeof import('@element-go/components')['ExLayout']
    ExLoading: typeof import('@element-go/components')['ExLoading']
    ExPageHeader: typeof import('@element-go/components')['ExPageHeader']
    ExPagination: typeof import('@element-go/components')['ExPagination']
    ExTable: typeof import('@element-go/components')['ExTable']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slot: typeof import('./src/components/slot.vue')['default']
  }
}
